name: audio_text_converter2
description: Application Flutter pour convertir audio en texte et texte en audio.

publish_to: "none" # projet privé

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  speech_to_text: ^7.0.0 
  flutter_tts: ^3.5.2
  font_awesome_flutter: ^10.4.0
  file_picker: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
